myproject/myapp/menu/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('menu_list/', views.menu_list, name='menu_list'),
]

myproject/myapp/urls.py
from django.conf import settings
from django.urls import include,re_path
from django.conf.urls.static import static
from django.urls import path
from django.views.static import serve
from .students import urls as students_urls
from .menu import urls as menu_urls
from . import views

urlpatterns = [
    path('',views.index, name='index'),
    path('menus/', include(menu_urls)),
    path('register/', views.register_views),
    path('form_regiter/',views.regiter_form_views),
    path('login/', views.login_views),
    path('form_login/', views.login_form_views),
    path('login_auto/', views.login_auto_views),
    path('students/', include(students_urls)),
    # 上传media的文件可以被查看，这个很重要，更后边的一个bug有关
    path(r'media/(?P<path>.*)', serve,{'document_root': settings.MEDIA_ROOT}),
    # 添加ckeditor的url到项目中
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # 上传的图片是到media中，不是在static中 所以需要设置media可被访问
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('myapp/', include('myapp.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path(r'media/(?P<path>.*)', serve, {'document_root': settings.MEDIA_ROOT}),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myproject/myapp/models.py
# Create your models here.
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.forms.models import model_to_dict


# 定义登录用户模型
class Users(models.Model):
    username = models.CharField(verbose_name='用户名', max_length=50, unique=True)
    password = models.CharField(verbose_name='密码', max_length=128)
    email = models.EmailField(verbose_name='邮箱', unique=True)
    age = models.IntegerField(verbose_name='年龄', null=True, blank=True)
    is_active = models.BooleanField(verbose_name='是否激活', default=True)
    is_admin = models.BooleanField(verbose_name='是否管理员', default=False)
    date_joined = models.DateTimeField(verbose_name='注册时间', auto_now_add=True)

    # 定义元类,指定数据表名称
    class Meta:
        db_table = 't_user'  # 指定数据表名称
        verbose_name = "用户信息"  # 指定页面显示应用名称
        verbose_name_plural = "用户信息"  # 指定页面显示应用名称,全量指定

    def __str__(self):
        return self.username


# 定义班级模型
class Class(models.Model):
    name = models.CharField(verbose_name='班级名称', max_length=50)  # 班级名称
    grade = models.CharField(verbose_name='年级', max_length=50)  # 年级
    # remarks = models.TextField(verbose_name='备注', blank=True)  # 备注
    # remarks = RichTextField(verbose_name='备注', blank=True)  # 备注
    remarks = RichTextUploadingField(verbose_name='备注', blank=True, config_name='default')
    teacher = models.ManyToManyField('Teacher', verbose_name='老师')

    # 定义元类,指定数据表名称
    class Meta:
        db_table = 't_class'  # 指定数据表名称
        verbose_name = "班级信息"  # 指定页面显示应用名称
        verbose_name_plural = "班级信息"  # 指定页面显示应用名称,全量指定

    # 定义一个返回的名称,默认返回self
    def __str__(self):
        return self.name


# 定义课程模型
class Course(models.Model):
    name = models.CharField(verbose_name='课程名称', max_length=50)
    teacher = models.ForeignKey('Teacher', verbose_name='教师', on_delete=models.CASCADE)
    price = models.DecimalField(verbose_name='课程价格', max_digits=10, decimal_places=2)
    remarks = RichTextUploadingField(verbose_name='备注', blank=True)

    # 定义元类,指定数据表名称
    class Meta:
        db_table = 't_course'  # 指定数据表名称
        verbose_name = "课程信息"  # 指定页面显示应用名称
        verbose_name_plural = "课程信息"  # 指定页面显示应用名称,全量指定
        # ordering = ['price']  # 指定排序字段

    def __str__(self):
        return self.name


# 定义老师模型
class Teacher(models.Model):
    name = models.CharField(verbose_name='教师姓名', max_length=50)
    GENDER_CHOICES = (
        ('', '请选择性别'),
        ('male', '男'),
        ('female', '女'),
    )
    sex = models.CharField(verbose_name='性别', max_length=10, choices=GENDER_CHOICES)  # 添加 choices 参数
    age = models.IntegerField(verbose_name='年龄', validators=[MinValueValidator(20), MaxValueValidator(100)])
    address = models.CharField(verbose_name='家庭住址', max_length=250, blank=True)
    remarks = RichTextUploadingField(verbose_name='备注', blank=True)

    # 定义元类,指定数据表名称
    class Meta:
        db_table = 't_teacher'  # 指定数据表名称
        verbose_name = "教师信息"  # 指定页面显示应用名称
        verbose_name_plural = "教师信息"  # 指定页面显示应用名称,全量指定
        # ordering = ['age']  # 指定排序字段

    def __str__(self):
        return self.name


# 定义学生模型
class Student(models.Model):
    name = models.CharField(verbose_name='学生姓名', max_length=50)
    # 定义性别选项
    GENDER_CHOICES = (
        # ('', '请选择性别'),
        ('male', '男'),
        ('female', '女'),
    )

    sex = models.CharField(verbose_name='性别', max_length=10, choices=GENDER_CHOICES)  # 添加 choices 参数
    age = models.IntegerField(verbose_name='年龄', validators=[MinValueValidator(1), MaxValueValidator(100)])
    image = models.ImageField(upload_to='images/', verbose_name='照片', blank=True, null=True)
    address = models.CharField(verbose_name='家庭住址', max_length=250, blank=True)
    enter_date = models.DateField(null=True, blank=True, verbose_name='入学时间')
    remarks = RichTextField(verbose_name='备注', blank=True)
    # 关联班级,空选项显示请选择
    sclass = models.ForeignKey("Class", on_delete=models.CASCADE, blank=True, null=True, verbose_name='班级',
                               default='请选择')

    # 定义元类,指定数据表名称
    class Meta:
        db_table = 't_student'  # 指定数据表名称
        verbose_name = "学生信息"  # 指定页面显示应用名称
        verbose_name_plural = "学生信息"  # 指定页面显示应用名称,全量指定
        # ordering = ['age']  # 指定排序字段

    def student_to_dict(student):
        return model_to_dict(student)

    # 精细地控制序列化的过程，可以手动创建字典：
    def student_to_dict_detail(student):
        return {
            'id': student.id,
            'name': student.name,
            'age': student.age,
            'sex': student.sex,
            'image': student.image.url if student.image else None,
            'address': student.address,  # 注意这里的address是字符串类型，需要用单引号包裹
            'class': student.sclass.name if student.sclass else None,
            'enter_date': student.enter_date
        }

    # 定义一个返回的名称,默认返回self
    def __str__(self):
        return self.name


# 定义学生班级关系模型
class StudentClass(models.Model):
    student = models.ForeignKey('Student', verbose_name='学生', on_delete=models.CASCADE)
    student_class = models.ForeignKey('Class', verbose_name='班级', on_delete=models.CASCADE)
    remarks = RichTextField(verbose_name='备注', blank=True)

    # 定义元类,指定数据表名称
    class Meta:
        db_table = 't_student_class'  # 指定数据表名称
        verbose_name = "学生班级关系"  # 指定页面显示应用名称
        verbose_name_plural = "学生班级关系"  # 指定页面显示应用名称,全量指定
        unique_together = ('student', 'student_class')  # 指定联合唯一索引


# 定义学生选课关系模型
class StudentCourse(models.Model):
    student = models.ForeignKey('Student', verbose_name='学生', on_delete=models.CASCADE)  # 学生
    course = models.ForeignKey('Course', verbose_name='课程', on_delete=models.CASCADE)  # 课程
    score = models.DecimalField(verbose_name='成绩', max_digits=10, decimal_places=2, null=True, blank=True)  # 成绩
    remarks = RichTextField(verbose_name='备注', blank=True)

    # 定义元类,指定数据表名称
    class Meta:
        db_table = 't_student_course'  # 指定数据表名称
        verbose_name = "学生选课关系"  # 指定页面显示应用名称
        verbose_name_plural = "学生选课关系"  # 指定页面显示应用名称,全量指定
        unique_together = ('student', 'course')  # 指定联合唯一索引


# 菜单模型
class Menu(models.Model):
    name = models.CharField(max_length=30, verbose_name='菜单名称')
    url = models.CharField(max_length=100, verbose_name='菜单URL')
    parent = models.ForeignKey('self', null=True, blank=True, on_delete=models.CASCADE, verbose_name='父菜单')
    order = models.IntegerField(verbose_name='排序', default=0)

    class Meta:
        verbose_name = '菜单'
        db_table = 't_menu'  # 指定数据表名称
        verbose_name_plural = verbose_name
        ordering = ['order']

    def __str__(self):
        return self.name

myproject/myapp/menu/views.py
from django.shortcuts import render
from ..models import Menu

def menu_list(request):
    menus = Menu.objects.all()
    return render(request, 'menus.html', {'menus': menus})

myproject/templates/basePage.html
<!-- basePage.html -->
<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="UTF-8">
   <meta http-equiv="Content-Type" name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=0.5, maximum-scale=2.0, user-scalable=yes"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>{% block title %}默认标题{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'layui/css/layui.css' %}">
    {% block extra_css %}
         <!-- 这里可以添加其他模板需要的额外头样式文件-->
    {% endblock %}
    <link rel="shortcut icon" href="{% static "images/favicon.ico" %}"/>

    {% block extra_style %}
    <!-- 这里可以添加其他模板需要的额外头部信息 -->
    {% endblock %}
</head>
<body>
    {% block content %}
    <!-- 这里将放置每个模板的内容 -->
    {% endblock %}

    <script src="{% static 'layui/layui.js' %}"></script>
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>

    {% block extra_scripts %}
    <!-- 这里可以添加其他模板需要的额外脚本信息 -->
    {% endblock %}
</body>
</html>

myproject/templates/index.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <title>欢迎使用我的网站</title>
    <meta charset="UTF-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
</head>
<body>
<div class="container">
    <div class="form-container">
        <div class="form-panel">
            <form action="/myapp/login_auto/" method="post">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="login-form">
                    <h1>登录</h1>
                    <section class="form-section">
                        <label for="username">账号</label>
                        <input type="text" id="username" name="username" placeholder="请输入用户名" required>
                        {% if form.username.errors %}
                            <span class="error-message"> {{ form.username.errors }}</span>
                        {% endif %}
                    </section>
                    <section class="form-section">
                        <label for="password">密码</label>
                        <input type="password" id="password" name="password" placeholder="请输入密码" required/>
                        {% if form.password.errors %}
                            <span class="error-message"> {{ form.password.errors }}</span>
                        {% endif %}
                    </section>
                    <span style="margin-bottom: 8px;">忘记密码?</span>

                    <button type="submit">登录</button>
                    <button type="button" class="alternative-login"> 使用<span
                            style="font-weight: 900; color: #455a81">二维码</span>登录
                    </button>
                </div>
            </form>
            <form action="/myapp/register/" method="post">
                {% csrf_token %}
                <div class="registration-form" style="display: none">
                    <h1>立即注册</h1>
                    <section class="form-section">
                        <label for="username">用户名</label>
                        <input type="text" id="username" name="username"/>
                    </section>
                    <section class="form-section">
                        <label for="email">邮箱</label>
                        <input type="text" id="email" name="email"/>
                    </section>
                    <section class="form-section">
                        <label for="password">密码</label>
                        <input type="password" name="password" id="password"/>
                    </section>
                    <button type="submit">1注册</button>
                    <button type="button" class="alternative-login"> 使用<span
                            style="font-weight: 900; color: #455a81">二维码</span>扫码注册
                    </button>
                </div>
            </form>
        </div>
        <div class="registration-panel">
            <h1 class="panel-title">还未注册？</h1>
            <span class="subTitle">立即注册，发现大量机会！</span>
            <button type="button" id="toggleForm" onclick="redirectToRegisterPage()">2注册</button>
        </div>
    </div>
</div>
<script src="{% static 'js/index.js' %}"></script>
<script>
    document.querySelector("input").addEventListener("invalid",
        function (event) {
            event.preventDefault();
        });

    function checkInput(input) {
        let spanElement = input.nextElementSibling;
        if (input.value && input.value.trim().length > 0) {
            debugger
            if (spanElement && spanElement.tagName.toLowerCase() === 'span') {
                spanElement.style.display = 'none';
            }
        }
    }

    window.onload = function () {
        // 获取所有input输入框元素
        var inputElement = document.querySelectorAll("input");
        // 为输入框添加失去焦点事件监听器
        for (var i = 0; i < inputElement.length; i++) {
            inputElement[i].addEventListener("blur", checkInput);
        }
    };

</script>
</body>
</html>

myproject/templates/login.html
<!DOCTYPE html>
<html lang="zh">
<head>
    <title>登录页面</title>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}">
</head>
<body>
     <form action="../login/" method="post">
         {% csrf_token %}
        <div class="login-container">
            <h2>登录</h2>
            <div class="input-group">
                <input type="text" name="username" placeholder="请输入用户名" required>
            </div>
            <div class="input-group">
                <input type="password" name="password" placeholder="请输入密码" required>
            </div>
            <button class="login-button">登录</button>
        </div>
     </form>
</body>
</html>

myproject/templates/login_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register_form</title>
</head>
<body>
     <p>{{ errmsg }}</p>
    <form action="../form_login/" method="post">
        {% csrf_token %}
            {{ form.as_p }}
        <p><input type="submit" value="登录"></p>
    </form>

</body>
</html>

myproject/templates/menus.html
{% extends 'basePage.html' %}
{% block title %}网站管理后台{% endblock %}

{% block extra_style %}
    <style>
        .layui-layout-admin .layui-header {
            background-color: #2d8cf0;
        }

        .layui-bg-cyan {
            background-color: #333333f0 !important;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="layui-layout layui-layout-admin">

        <div class="layui-header">
            <div class="layui-logo" style="color: white; font-size: 20px;">迅捷资源管理系统</div>
            <!-- 头部区域（可配合layui 已有的水平导航） -->
            <ul class="layui-nav layui-layout-left">

                <!-- web、移动端显示 -->
                <li class="layui-nav-item layui-show-xs-inline-block " lay-header-event="menuLeft">
                    <a href="javascript:;" title="展示或者隐藏垂直工具栏"> <i id="leftEnumIcon"
                                                                              class="layui-icon layui-icon-spread-left"></i></a>
                </li>

                <!--刷新当前页面-->
                <li class="layui-nav-item layui-hide-xs">
                    <a href="javascript:;" onclick="window.location.reload()" title="刷新页面">
                        <i class="layui-icon layui-icon-refresh-1" style="color: #eeffef;"></i>
                    </a>
                </li>
            </ul>
            <ul class="layui-nav layui-layout-right">
                <li class="layui-nav-item layui-hide layui-show-md-inline-block">
                    <a href="javascript:;">
                        <img src="https://b-ssl.duitang.com/uploads/item/201709/30/20170930100815_UXS2k.gif"
                             class="layui-nav-img">
                        nickname or username
                    </a>
                    <dl class="layui-nav-child">
                        <dd><a href="">登录信息</a></dd>
                        <dd><a href="">设置</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item layui-hide layui-show-md-inline-block">
                    <a href="javascript:;"> 登出 </a>
                </li>

                <!--右侧消息栏-->
                <!--<li class="layui-nav-item" lay-header-event="menuRight" lay-unselect>-->
                <!--<a href="javascript:;">-->
                <!--<i class="layui-icon layui-icon-more-vertical"></i>-->
                <!--</a>-->
                <!--</li>-->
            </ul>
        </div>

        <!--左侧管理栏目-->
        <div class="layui-side layui-bg-cyan">
            <div class="layui-side-scroll">
                <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
                <ul class="layui-nav layui-nav-tree" lay-filter="nav-tree">
                    {% for menu in menus %}
                        {% if not menu.parent %}
                            <li class="layui-nav-item" data-index="{{ forloop.counter }}">
                                <a href="javascript:;" data-url="{{ menu.url }}">{{ menu.name }}</a>
                                {% if menu.menu_set.all %}
                                    <dl class="layui-nav-child">
                                        {% for sub_menu in menu.menu_set.all %}
                                            <dd><a class="site-tab-active" data-url="{{ sub_menu.url }}"
                                                   href="javascript:;"
                                                   data-type="tabAdd" data-id="{{ sub_menu.order }}"
                                                   data-title="{{ sub_menu.name }}">{{ sub_menu.name }}</a>
                                            </dd>
                                        {% endfor %}
                                    </dl>
                                {% endif %}
                            </li>
                        {% endif %}
                    {% endfor %}

                    <li class="layui-nav-item">
                        <a class="" href="javascript:;">博客日记</a>
                        <dl class="layui-nav-child">
                            <dd><a class="site-tab-active" data-url="/admin/article/type" data-type="tabAdd"
                                   data-id="leixingguanli" data-title="类型管理"
                                   href="javascript:;">类型管理</a></dd>
                            <dd><a class="site-tab-active" data-url="/admin/article1/type2" data-type="tabAdd"
                                   data-id="wenzgl" data-title="文章管理" href="javascript:;">文章管理</a></dd>
                            <dd><a href="javascript:;">公告管理</a></dd>
                        </dl>
                    </li>
                    <!--layui-nav-itemed 默认展示而不是折叠-->
                    <li class="layui-nav-item ">
                        <a class="" href="javascript:;">广告管理</a>
                        <dl class="layui-nav-child">
                            <dd><a href="javascript:;">首页广告</a></dd>
                            <dd><a href="javascript:;">边栏广告</a></dd>
                            <dd><a href="javascript:;">条形广告</a></dd>
                        </dl>
                    </li>

                    <li class="layui-nav-item">
                        <a href="javascript:;">用户管理</a>
                        <dl class="layui-nav-child">
                            <dd><a href="javascript:;">用户信息</a></dd>
                            <dd><a href="javascript:;">角色信息</a></dd>
                        </dl>
                    </li>
                    <li class="layui-nav-item">
                        <a data-url="/news_list" data-id="3" data-title="新闻列表" class="site-tab-active"
                           href="javascript:;" data-type="tabAdd">新闻列表</a>
                    </li>
                    <li class="layui-nav-item"><a href="javascript:;">标签管理</a></li>
                    <li class="layui-nav-item"><a href="">链接管理</a></li>
                    <li class="layui-nav-item"><a href="">留言管理</a></li>
                    <li class="layui-nav-item">
                        <a href="javascript:;">系统设置</a>
                        <dl class="layui-nav-child">
                            <dd><a href="javascript:;">版权设置</a></dd>
                            <dd><a href="javascript:;">OSS设置</a></dd>
                            <dd><a href="javascript:;">图片设置</a></dd>
                        </dl>
                    </li>
                    <li class="layui-nav-item">
                        <a href="javascript:;">实时数据</a>
                        <dl class="layui-nav-child">
                            <dd><a href="javascript:;">实时监控</a></dd>
                            <dd><a href="javascript:;">实时日志</a></dd>
                        </dl>
                    </li>
                </ul>
            </div>
        </div>

        <!--body页面-->
        <div class="layui-body">

            <div class="layui-tab" lay-filter="tab" lay-allowclose="true">
                <ul class="layui-tab-title">
                    <li class="layui-this" lay-id="index">首页</li>
                </ul>

                <div class="layui-tab-content">
                    <div class="layui-tab-item layui-show">
                        <!--正文-->
                        <fieldset class="layui-elem-field layui-field-title" style="margin-top: 20px;">
                            <legend>正文...</legend>
                        </fieldset>

                    </div>
                </div>
            </div>

            <!--新增tab 删除tab  切换tab-->
            <!--<div class="site-tab-button" style="margin-bottom: 0;">-->
            <!--<button class="layui-btn site-tab-active" data-type="tabAdd">新增Tab项</button>-->
            <!--<button class="layui-btn site-tab-active" data-type="tabDelete">删除：商品管理</button>-->
            <!--<button class="layui-btn site-tab-active" data-type="tabChange">切换到：用户管理</button>-->
            <!--</div>-->
        </div>

        <!--footer界面-->
        <div class="layui-footer">
            <!-- 底部固定区域 -->
            Copyright: <span id="copyrightIntro">@2026-2029</span>
            备案号： <a href="http://beian.miit.gov.cn" target="_blank"><span id="icp">1111111</span></a>
            <a target="_blank" href="http://beian.miit.gov.cn"
               style="display:inline-block; text-decoration:none;height:20px;line-height:20px;">
                <img tsrc="/layui/images/face/0.gif" style="float:left;"/>
                <span id="addrIcp"> 66666</span>
            </a>
        </div>
    </div>
{% endblock %}

{% block extra_scripts %}
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
    <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
    <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <script>
        layui.use(['layer'], function () {
            var layer = layui.layer;
            // 其他需要使用 layer 的代码
        });

        layui.use(['util', 'element'], function () {
            var element = layui.element;
            var util = layui.util;
            // var $ = layui.jquery;

            //触发tab事件
            var active = {
                //在这里给active绑定几项事件，后面可通过active调用这些事件
                tabAdd: function (url, id, name) {
                    //新增一个Tab项 传入三个参数，分别对应其标题，tab页面的地址，还有一个规定的id，是标签中data-id的属性值
                    //关于tabAdd的方法所传入的参数可看layui的开发文档中基础方法部分
                    element.tabAdd('tab', {
                        title: name,
                        content: '<iframe onload="FrameWH()" height="100%" width="100%" scrolling="auto" data-frameid="' + id + '"  frameborder="0" src="' + url + '">  </iframe>',
                        id: id //规定好的id
                    })
                    element.render('tab');

                },
                tabChange: function (id) {
                    //切换到指定Tab项
                    element.tabChange('tab', id); //根据传入的id传入到指定的tab项
                },
                tabDelete: function (id) {
                    element.tabDelete("tab", id);//删除
                }
                , tabDeleteAll: function (ids) {//删除所有
                    $.each(ids, function (i, item) {
                        element.tabDelete("tab", item); //ids是一个数组，里面存放了多个id，调用tabDelete方法分别删除
                    })
                }
            };
            //当点击有site-tab-active属性的标签时，即左侧菜单栏中内容 ，触发点击事件
            $('.site-tab-active').on('click', function () {
                var dataid = $(this);
                //这时会判断右侧.layui-tab-title属性下的有lay-id属性的li的数目，即已经打开的tab项数目
                if ($(".layui-tab-title li[lay-id]").length <= 0) {
                    //如果比零小，则直接打开新的tab项
                    active.tabAdd(dataid.attr("data-url"), dataid.attr("data-id"), dataid.attr("data-title"));
                } else {
                    //否则判断该tab项是否以及存在
                    var isData = false; //初始化一个标志，为false说明未打开该tab项 为true则说明已有
                    $.each($(".layui-tab-title li[lay-id]"), function () {
                        //如果点击左侧菜单栏所传入的id 在右侧tab项中的lay-id属性可以找到，则说明该tab项已经打开
                        if ($(this).attr("lay-id") == dataid.attr("data-id")) {
                            isData = true;
                        }
                    })
                    if (isData == false) {
                        //标志为false 新增一个tab项
                        active.tabAdd(dataid.attr("data-url"), dataid.attr("data-id"), dataid.attr("data-title"));
                    }
                }
                //最后不管是否新增tab，最后都转到要打开的选项页面上
                active.tabChange(dataid.attr("data-id"));
            });

            //头部事件
            util.event('lay-header-event', {  //util 记得 声明 var util = layui.util
                //左侧菜单事件
                menuLeft: function (othis) {
                    var btn = $("#leftEnumIcon");
                    if (btn.hasClass('layui-icon-spread-left')) {
                        menuHide(btn);
                        btn.addClass('btn-index');
                    } else if (btn.has('layui-icon-shrink-right')) {
                        btn.removeClass('btn-index');
                        menuShow(btn);
                    }
                }
            });
        })

        /*处理左侧栏的信息的三个方法*/
        $(window).resize(function () {
            var width = $(document.body).width();
            var btn = $("leftEnumIcon");
            if (width < 1000) {
                if (btn.hasClass('layui-icon-spread-left')) {
                    menuShow(btn);
                }
            } else {
                if (!btn.hasClass('btn-index')) {
                    if (btn.hasClass('layui-icon-shrink-right')) {
                        menuHide(btn);
                    }
                }
            }
        });

        /*展示左侧栏*/
        function menuShow(btn) {
            btn.removeClass('layui-icon-shrink-right').addClass('layui-icon-spread-left');
            $(".layui-side").animate({width: 'toggle'});
            $(".zq-logo").animate({width: 'toggle'});
            $(".layui-body").animate({left: '200px'});
            $(".layui-footer").animate({left: '200px'});
        }

        /*隐藏左侧栏*/
        function menuHide(btn) {
            btn.removeClass(' layui-icon-spread-left').addClass('layui-icon-shrink-right');
            $(".layui-side").animate({width: 'toggle'}); //toggle如果原来div是隐藏的就会把元素显示，如果原来是显示则隐藏
            $(".zq-logo").animate({width: 'toggle'});
            $(".layui-body").animate({left: '0px'});
            $(".layui-footer").animate({left: '0px'});
        }

        /*iframe 高度自适应事件*/
        function FrameWH() {
            var h = $(window).height() - 200;
            $("iframe").css("height", h + "px");
            $(window).resize(function () {
                FrameWH();
            });
        }
    </script>
{% endblock %}

myproject/templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>用户注册</title>
</head>
<body>
    <p>{{ errmsg }}</p>
    <form action="../register/" method="post">
     {% csrf_token %}
        {% for form in forms %}
            <p>{{ form.label }}{{ form }}</p>
        {% endfor %}
        <p><input type="submit" value="注册"></p>
    </form>
</body>
</html>

myproject/templates/register_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
     <p>{{ errmsg }}</p>
    <form action="../form_regiter/" method="post">
        {% csrf_token %}
            {{ form.as_p }}
        <p><input type="submit" value="注册"></p>
    </form>

</body>
</html>